env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1

dist: focal
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements_build.txt

script:
  - py.test -v

after_success:
  - codecov
